#!/usr/bin/perl

our $TARGET = 'CheatSheet.tex';
$|=1;

my @revisionlist = `LANG=C svn info -R | grep "^Revision"`;
my @revisionlist = sort(@revisionlist);
my $revision = pop(@revisionlist);

chomp($revision);

my @status = `LANG=C svn st | grep "tex\$" | grep "^M"`;
if(@status > 0){ $revision .= "+"; }

my $date = `date +%Y.%m.%d`;
chomp($date);

my $text = "\\\\def\\\\headermark{$date \\/ $revision}";

my $before = `grep '\\\\def\\\\headermark' $TARGET`;
unless($before =~ /$text/){
   `sed -i .bak 's/\\\\def\\\\headermark.*/$text/' $TARGET`;
}
print `platexmk $TARGET`;

exit 0;
