#!/bin/bash

git clean -xf feynman

platex CheatSheet

(
  cd feynman
  for i in *.mp; do
    if [ "$i" != "feynmp.mp" ]; then
      mpost $i
    fi
  done
)

rm *.dvi
platex CheatSheet
platex CheatSheet
platex --shell-escape CheatSheet
dvipdfmx CheatSheet
