# -*- coding: utf-8 -*-
from pygments.formatters.latex import LatexFormatter
import re


class Wrapper():
    def __init__(self, tokensource):
        self._source = tokensource

    def wrap(self, text):
        return re.sub(r'\\\[(\w+)\]', lambda m: dictionary.get(m[1], m[0]), text)

    def __iter__(self):
        for category, token in self._source:
            yield category, self.wrap(token)


class CustomFormatter(LatexFormatter):
    def __init__(self, **options):
        super().__init__(**options)

    def format_unencoded(self, tokensource, outfile):
        super().format_unencoded(Wrapper(tokensource), outfile)


dictionary = {
    "Aleph" : u'ℵ',
    "Alpha" : u'α',
    "Angle" : u'∠',
    "Angstrom": u'Å',
    "AscendingEllipsis": u'⋰',
    "Backslash": u'∖',
    "BeamedEighthNote": u'♫',
    "BeamedSixteenthNote": u'♬',
    "Bet": u'ℶ',
    "Beta": u'β',
    "Bullet": u'•',
    "CapitalAlpha": u'Α',
    "CapitalBeta": u'Β',
    "CapitalChi": u'Χ',
    "CapitalDelta": u'Δ',
    "CapitalDigamma": u'Ϝ',
    "CapitalEpsilon": u'Ε',
    "CapitalEta": u'Η',
    "CapitalGamma": u'Γ',
    "CapitalIota": u'Ι',
    "CapitalKappa": u'Κ',
    "CapitalKoppa": u'Ϟ',
    "CapitalLambda": u'Λ',
    "CapitalMu": u'Μ',
    "CapitalNu": u'Ν',
    "CapitalOmega": u'Ω',
    "CapitalOmicron": u'Ο',
    "CapitalPhi": u'Φ',
    "CapitalPi": u'Π',
    "CapitalPsi": u'Ψ',
    "CapitalRho": u'Ρ',
    "CapitalSampi": u'Ϡ',
    "CapitalSigma": u'Σ',
    "CapitalStigma": u'Ϛ',
    "CapitalTau": u'Τ',
    "CapitalTheta": u'Θ',
    "CapitalUpsilon": u'Υ',
    "CapitalXi": u'Ξ',
    "CapitalZeta": u'Ζ',
    "Cap": u'⌢',
    "CenterEllipsis": u'⋯',
    "Checkmark": u'✓',
    "Chi": u'χ',
    "CloseCurlyDoubleQuote": u'”',
    "CloseCurlyQuote": u'’',
    "CloverLeaf": u'⌘',
    "ClubSuit": u'♣',
    "CurlyCapitalUpsilon": u'ϒ',
    "CurlyEpsilon": u'ε',
    "CurlyKappa": u'ϰ',
    "CurlyPhi": u'φ',
    "CurlyPi": u'ϖ',
    "CurlyRho": u'ϱ',
    "CurlyTheta": u'ϑ',
    "Dagger": u'†',
    "Dalet": u'ℸ',
    "Dash": u'–',
    "Delta": u'δ',
    "DescendingEllipsis": u'⋱',
    "Diameter": u'⌀',
    "Diamond": u'⋄',
    "DiamondSuit": u'♢',
    "Digamma": u'ϝ',
    "DoubleDagger": u'‡',
    "DoublePrime": u'″',
    "Earth": u'♁',
    "EighthNote": u'♪',
    "Ellipsis": u'…',
    "EmptyCircle": u'○',
    "EmptyDiamond": u'◇',
    "EmptyDownTriangle": u'▽',
    "EmptyRectangle": u'▯',
    "EmptySet": u'∅',
    "EmptySmallCircle": u'◦',
    "EmptySmallSquare": u'◻',
    "EmptySquare": u'□',
    "EmptyUpTriangle": u'△',
    "EmptyVerySmallSquare": u'▫',
    "Epsilon": u'ϵ',
    "Eta": u'η',
    "Euro": u'€',
    "FilledCircle": u'●',
    "FilledDiamond": u'◆',
    "FilledDownTriangle": u'▼',
    "FilledLeftTriangle": u'◀',
    "FilledRectangle": u'▮',
    "FilledRightTriangle": u'▶',
    "FilledSmallSquare": u'◼',
    "FilledSquare": u'■',
    "FilledUpTriangle": u'▲',
    "FilledVerySmallSquare": u'▪',
    "FinalSigma": u'ς',
    "FivePointedStar": u'★',
    "Flat": u'♭',
    "Gamma": u'γ',
    "Gimel": u'ℷ',
    "GothicCapitalC": u'ℭ',
    "GothicCapitalH": u'ℌ',
    "GothicCapitalI": u'ℑ',
    "GothicCapitalR": u'ℜ',
    "GothicCapitalZ": u'ℨ',
    "HappySmiley": u'☺',
    "HBar": u'ℏ',
    "HeartSuit": u'♡',
    "HorizontalLine": u'─',
    "Hyphen": u'‐',
    "Iota": u'ι',
    "Jupiter": u'♃',
    "Kappa": u'κ',
    "Koppa": u'ϟ',
    "Lambda": u'λ',
    "Mars": u'♂',
    "MeasuredAngle": u'∡',
    "Mercury": u'☿',
    "Mho": u'℧',
    "Micro": u'µ',
    "MinusPlus": u'∓',
    "Mu": u'μ',
    "Nand": u'⊼',
    "Natural": u'♮',
    "Neptune": u'♆',
    "Nu": u'ν',
    "Omega": u'ω',
    "Omicron": u'ο',
    "OpenCurlyDoubleQuote": u'“',
    "OpenCurlyQuote": u'‘',
    "Or": u'∨',
    "OverBracket": u'⎴',
    "Paragraph": u'¶',
    "PartialD": u'∂',
    "Phi": u'ϕ',
    "Pi": u'π',
    "PlusMinus": u'±',
    "Pluto": u'♇',
    "Prime": u'′',
    "Psi": u'ψ',
    "QuarterNote": u'♩',
    "ReturnIndicator": u'↵',
    "ReverseDoublePrime": u'‶',
    "ReversePrime": u'‵',
    "Rho": u'ρ',
    "RightAngle": u'∟',
    "SadSmiley": u'☹',
    "Sampi": u'ϡ',
    "Saturn": u'♄',
    "ScriptCapitalB": u'ℬ',
    "ScriptCapitalE": u'ℰ',
    "ScriptCapitalF": u'ℱ',
    "ScriptCapitalH": u'ℋ',
    "ScriptCapitalI": u'ℐ',
    "ScriptCapitalL": u'ℒ',
    "ScriptCapitalM": u'ℳ',
    "ScriptCapitalR": u'ℛ',
    "ScriptE": u'ℯ',
    "ScriptG": u'ℊ',
    "ScriptL": u'ℓ',
    "ScriptO": u'ℴ',
    "Sharp": u'♯',
    "Sigma": u'σ',
    "SixPointedStar": u'✶',
    "SkeletonIndicator": u'⁃',
    "SmallCircle": u'∘',
    "SpaceIndicator": u'␣',
    "SpadeSuit": u'♠',
    "SphericalAngle": u'∢',
    "Star": u'⋆',
    "Stigma": u'ϛ',
    "Tau": u'τ',
    "Theta": u'θ',
    "Tilde": u'∼',
    "Trademark": u'™',
    "UnderBracket": u'⎵',
    "UpPointer": u'▴',
    "Upsilon": u'υ',
    "Uranus": u'♅',
    "Venus": u'♀',
    "VerticalEllipsis": u'⋮',
    "VerticalLine": u'│',
    "WeierstrassP": u'℘',
    "Xi": u'ξ',
    "Zeta": u'ζ',
}
